const urls = {
    login: '/auth/login',
    userinfo: '/account/userinfo',
    addType: '/type/add',
    editType: '/type/edit',
    getType: '/type/list',
    getTypes: '/type/query',
    delType: '/type/del',
    addLabel: '/labels/add',
    editLabel: '/labels/edit',
    getLabel: '/labels/list',
    getLabels: '/labels/query',
    delLabel: '/labels/del',
    addArticle: '/article/add',
    editArticle: '/article/edit',
    saveArticle: '/article/save',
    getArticle: '/article/list',
    getArticles: '/article/query',
    getArticleInfo: '/article/detail',
    delArticle: '/article/del',
    uploadimg: '/upload/img',
}
export default urls